# -*- coding: utf-8 -*-
"""tasala stock marketing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-ZwzLLcQ-WCxduNHvVwnlUkwvlipQla
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('/content/TSLA.CSV')

data

data.shape

data

data.head().T

data.info()

stock_data = data[["Date", "Close"]] # Changed "data" to "Date" and "close" to "Close" assuming this is the correct column names

stock_data

stock_data.info() # data column is object , idealy it should be data time

stock_data["Data"] = pd.to_datetime(stock_data["Date"])

stock_data.info()

stock_data

# time series data and tradition data>> the difference is time series has a time componet
# therefore data  colun should be index
# slicing  od data on date columns beacomes easy
# visulazation is simple
# libaries  realted to forecasting model ossumnes that there  is a time\ data column

stock_data.set_index("Data")

stock_data

stock_data.describe()

plt.plot (stock_data["Close"])

plt.plot(stock_data["Data"])

plt.hist(stock_data.Close)

plt.hist(stock_data.Data)

plt.style.use('ggplot')
plt.figure(figsize=(18,8))
plt.grid(True)
plt.xlabel('Date', fontsize = 20) # Changed fontsizes to fontsize
plt.xticks(fontsize = 15)
plt.ylabel('Close Prices', fontsize = 20) # Changed fontsizes to fontsize and corrected the typo in plt.ylable
plt.xticks(fontsize = 15)
plt.plot(stock_data['Close'], linewidth = 3, color = 'blue')
plt.title('stock closing price', fontsize = 30) # Corrected the typo in plt.tittle
plt.show()

plt.style.use('ggplot')
plt.figure(figsize=(18,8))
plt.grid(True)
plt.xlabel('Dates', fontsize = 20) # Changed fontsizes to fontsize
plt.xticks(fontsize = 15)
plt.ylabel('Close Prices', fontsize = 20) # Changed fontsizes to fontsize and corrected the typo in plt.ylable
plt.xticks(fontsize = 15)
plt.hist(stock_data['Close'], linewidth = 3, color = 'blue')
plt.title('stock closing price', fontsize = 30) # Corrected the typo in plt.tittle
plt.show()

#distributaion of closing price
df_close = stock_data['Close']
df_close.plot (kind ='kde' , figsize =(18,8), linewidth = 3) # Changed 'kid' to 'kde'
plt.xticks(fontsize = 15)
plt.grid("both")
plt.ylabel("Density", fontsize = 20)
plt.yticks(fontsize = 15)
plt.show()

rolling_mean = stock_data['Close'].rolling(48).mean()
rolling_std = stock_data['Close']. rolling(48).std()

rolling_std

plt.plot(stock_data.Close)
plt.plot(rolling_mean, color = 'red')
plt.plot(rolling_std, color ='green')

plt.plot(stock_data.Close)
plt.plot(rolling_mean)
plt.plot(rolling_std)